import = ["~/.config/alacritty/tokyonight_storm.toml"]
[font]
size = 19
[font.normal]
family = "PragmataProMonoLiga Nerd Font"
style = "Regular"
[font.bold]
family = "PragmataProMonoLiga Nerd Font"
style = "Bold"
[font.italic]
family = "PragmataProMonoLiga Nerd Font"
style = "Italic"
[font.bold_italic]
family = "PragmataProMonoLiga Nerd Font"
style = "Bold Italic"

[window]
padding = { x = 9, y = 9 }
decorations = "Buttonless"
dynamic_padding = true
option_as_alt = "Both"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [{ key = "Key6", mods = "Control", chars = "\u001e" }]
